version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000

    # Our project files get their environment variables (environ) from below (not from .env)
    # What about .env ? we use its variable inside ${} to avoid inserting plain text here
    environment:
      - DB_HOST=${DOCKER_DB_HOST}
    depends_on:
      db:
        # Based on health check
        condition: service_healthy
      
  db:
    image: postgres

    container_name: social-db-container

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - C:\Users\sadeq\Desktop\data:/var/lib/postgresql/data

    restart: always

    # set shared memory limit when using docker-compose
    shm_size: 128mb

    # Determine when the db is accepted as healthy
    healthcheck:

      # test takes two aruments ["executable", "arg"]
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
  # foo:
  #   # # If below is not specifyed, docker will use other volume (projectname_postgres_data)
  #   external: true