# Generated by Django 5.0.1 on 2024-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_client_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='channel_name',
            field=models.CharField(max_length=1000),
        ),
    ]
