# Generated by Django 5.0.1 on 2024-02-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_file_delete_filemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread',
            new_name='room',
        ),
    ]
