# Generated by Django 4.2.4 on 2023-10-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_securityanswer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSecurityQuestion',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
