# Generated by Django 4.2.4 on 2023-09-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover',
        ),
    ]
