# Generated by Django 4.2.4 on 2023-09-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_image_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
