# Generated by Django 4.2.4 on 2023-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_commentlike_unique_comment_likers_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentlike',
            name='unique_comment_likers',
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_comment_likers'),
        ),
    ]
